name: "YOLO_N_INT8"
platform: "onnxruntime_onnx"
max_batch_size: 0
input {
  name: "INPUT__0"
  data_type: TYPE_FP32
  dims: 1
  dims: 3
  dims: 224
  dims: 224
}
output {
  name: "OUTPUT__0"
  data_type: TYPE_FP32
  dims: 1
  dims: 3
  dims: 224
  dims: 224
}
