"""
AUTO-GENERATED WRAPPER.

DO NOT EDIT THIS FILE DIRECTLY.

Source of truth:
  - sdk/src/tcm_client/sdk.py

This wrapper exists so repo-local tests and examples can keep importing from
`MANAGER/_______WEBSOCKET/sdk.py` without duplicating SDK logic.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Make `tcm_client` importable from the repo checkout without installation.
_repo_root = Path(__file__).resolve().parents[3]
_sdk_src = _repo_root / "sdk" / "src"
sys.path.insert(0, str(_sdk_src))

from tcm_client.sdk import (  # noqa: E402
    AuthContext,
    TcmWebSocketClient,
    quickstart_queue_stats,
    run_quickstart,
)

__all__ = ["AuthContext", "TcmWebSocketClient", "quickstart_queue_stats", "run_quickstart"]
