"""
Synchronize the vendored (repo-internal) WebSocket SDK wrapper with the packaged SDK.

Source of truth:
  - sdk/src/tcm_client/sdk.py

Vendored wrapper (used by repo tests and internal examples):
  - apps/manager/_______WEBSOCKET/sdk.py

Usage:
  python3 scripts/sync_sdk.py
  python3 scripts/sync_sdk.py --check
"""

from __future__ import annotations

import argparse
from pathlib import Path


HEADER = """\"\"\"AUTO-GENERATED WRAPPER.

DO NOT EDIT THIS FILE DIRECTLY.

Source of truth:
  - sdk/src/tcm_client/sdk.py

To regenerate:
  - python3 scripts/sync_sdk.py
\"\"\"

"""


WRAPPER = """from __future__ import annotations

import sys
from pathlib import Path

# Make `tcm_client` importable from the repo checkout without installation.
_repo_root = Path(__file__).resolve().parents[2]
_sdk_src = _repo_root / "sdk" / "src"
sys.path.insert(0, str(_sdk_src))

from tcm_client.sdk import (  # noqa: E402
    AuthContext,
    TcmWebSocketClient,
    quickstart_queue_stats,
    run_quickstart,
)

__all__ = [
    "AuthContext",
    "TcmWebSocketClient",
    "quickstart_queue_stats",
    "run_quickstart",
]
"""


def build_expected() -> str:
    return HEADER + WRAPPER


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if vendored SDK is out of sync.",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    src = repo_root / "sdk" / "src" / "tcm_client" / "sdk.py"
    dest = repo_root / "apps" / "manager" / "_______WEBSOCKET" / "sdk.py"

    if not src.exists():
        raise SystemExit(f"Source not found: {src}")
    if not dest.exists():
        raise SystemExit(f"Destination not found: {dest}")

    expected = build_expected()
    current = dest.read_text(encoding="utf-8")

    if args.check:
        return 0 if current == expected else 1

    dest.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

