name: "TCM_TINY"
platform: "onnxruntime_onnx"
default_model_filename: "weights/model.onnx"
max_batch_size: 0
input {
  name: "INPUT__0"
  data_type: TYPE_FP32
  dims: 1
}
output {
  name: "OUTPUT__0"
  data_type: TYPE_FP32
  dims: 1
}
